export enum MimeType {
  aac = 'audio/aac',
  abw = 'application/x-abiword',
  arc = 'application/x-freearc',
  avi = 'video/x-msvideo',
  azw = 'application/vnd.amazon.ebook',
  bin = 'application/octet-stream',
  bmp = 'image/bmp',
  bz = 'application/x-bzip',
  bz2 = 'application/x-bzip2',
  cda = 'application/x-cdf',
  csh = 'application/x-csh',
  css = 'text/css',
  csv = 'text/csv',
  doc = 'application/msword',
  docx = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  eot = 'application/vnd.ms-fontobject',
  epub = 'application/epub+zip',
  gz = 'application/gzip',
  gif = 'image/gif',
  htm = 'text/html',
  html = 'text/html',
  ico = 'image/vnd.microsoft.icon',
  ics = 'text/calendar',
  jar = 'application/java-archive',
  jpeg = 'image/jpeg',
  jpg = 'image/jpeg',
  js = 'text/javascript',
  json = 'application/json',
  jsonld = 'application/ld+json',
  mid = 'audio/midi',
  midi = 'audio/x-midi',
  mjs = 'text/javascript',
  mp3 = 'audio/mpeg',
  mp4 = 'video/mp4',
  mpeg = 'video/mpeg',
  mpkg = 'application/vnd.apple.installer+xml',
  odp = 'application/vnd.oasis.opendocument.presentation',
  ods = 'application/vnd.oasis.opendocument.spreadsheet',
  odt = 'application/vnd.oasis.opendocument.text',
  oga = 'audio/ogg',
  ogv = 'video/ogg',
  ogx = 'application/ogg',
  opus = 'audio/opus',
  otf = 'font/otf',
  png = 'image/png',
  pdf = 'application/pdf',
  php = 'application/x-httpd-php',
  ppt = 'application/vnd.ms-powerpoint',
  pptx = 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  rar = 'application/vnd.rar',
  rtf = 'application/rtf',
  sh = 'application/x-sh',
  svg = 'image/svg+xml',
  swf = 'application/x-shockwave-flash',
  tar = 'application/x-tar',
  tif = 'image/tiff',
  tiff = 'image/tiff',
  ts = 'video/mp2t',
  ttf = 'font/ttf',
  txt = 'text/plain',
  vsd = 'application/vnd.visio',
  wav = 'audio/wav',
  weba = 'audio/webm',
  webm = 'video/webm',
  webp = 'image/webp',
  woff = 'font/woff',
  woff2 = 'font/woff2',
  xhtml = 'application/xhtml+xml',
  xls = 'application/vnd.ms-excel',
  xlsx = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  xml = 'application/xml',
  xul = 'application/vnd.mozilla.xul+xml',
  zip = 'application/zip',
  video3gp = 'video/3gpp',
  audio3gp = 'audio/3gpp',
  video3g2 = 'video/3gpp2',
  audio3g2 = 'audio/3gpp2',
  zip7 = 'application/x-7z-compressed',
}

export const previewBlobType: Record<string, MimeType> = {
  pdf: MimeType.pdf,
  jpg: MimeType.jpg,
  jpeg: MimeType.jpeg,
  png: MimeType.png,
  bmp: MimeType.bmp,
  doc: MimeType.doc,
  docx: MimeType.docx,
  xls: MimeType.xls,
  xlsx: MimeType.xlsx,
}

enum ALLOWFILETYPEENUM {
  PDF = 'PDF',
  PNG = 'PNG',
  JPEG = 'JPEG',
  JPG = 'JPG',
  DOCS = 'DOCS',
  XLS = 'XLS',
  XLSX = 'XLSX',
}

const allowFileTypeDisplayValue = {
  PDF: { label: ALLOWFILETYPEENUM.PDF, value: MimeType.pdf },
  JPG: { label: ALLOWFILETYPEENUM.JPG, value: MimeType.jpg },
  JPEG: { label: ALLOWFILETYPEENUM.JPEG, value: MimeType.jpeg },
  PNG: { label: ALLOWFILETYPEENUM.PNG, value: MimeType.png },
  DOCS: { label: ALLOWFILETYPEENUM.DOCS, value: MimeType.docx },
  XLS: { label: ALLOWFILETYPEENUM.XLS, value: MimeType.xls },
  XLSX: { label: ALLOWFILETYPEENUM.XLSX, value: MimeType.xlsx },
}

export const allowedFileTypeOption = [
  {
    label: allowFileTypeDisplayValue.PDF.label,
    value: allowFileTypeDisplayValue.PDF.label,
  },
  {
    label: allowFileTypeDisplayValue.JPG.label,
    value: allowFileTypeDisplayValue.JPG.label,
  },
  {
    label: allowFileTypeDisplayValue.JPEG.label,
    value: allowFileTypeDisplayValue.JPEG.label,
  },
  {
    label: allowFileTypeDisplayValue.PNG.label,
    value: allowFileTypeDisplayValue.PNG.label,
  },
  {
    label: allowFileTypeDisplayValue.DOCS.label,
    value: allowFileTypeDisplayValue.DOCS.label,
  },

  {
    label: allowFileTypeDisplayValue.XLS.label,
    value: allowFileTypeDisplayValue.XLS.label,
  },
  {
    label: allowFileTypeDisplayValue.XLSX.label,
    value: allowFileTypeDisplayValue.XLSX.label,
  },
]

export enum DOCUMENTMODULENAME {
  REGISTRATION_BOOK = 'REGISTRATION_BOOK',
  DISPATCH_BOOK = 'DISPATCH_BOOK',
  STANDING_LIST = 'STANDING_LIST',
}
