export const privateRoutePath = {
  root: "/",
  dashboard: "/dashboard",
  security: "/security",
  userSetup: "/security/user-setup",
  roleSetup: "/security/role-setup",
  moduelSetup: "/security/module-setup",
  resourceSetup: "/security/resource-setup",
  roleModuleSetup: '/security/role-module',
  roleModuleMappingSetup: '/security/role-module/:roleId',
  masterData: "/master-data",
  sectorSetup: "/master-data/sector-setup",
  subSectorSetup: "/master-data/sub-sector-setup",
  gdpSetup: "/master-data/gdp-setup",
  climateSetup: "/master-data/climate-setup",
  genderSensitiveSetup: "/master-data/gender-sensitive-setup",
  strategyPedestalSetup: "/master-data/strategy-pedestal-setup",
  sustainableDevelopmentGoalSetup:
    "/master-data/sustainable-goal-development-setup",
  fiscalYearSetup: "/master-data/fiscal-year-setup",
  sectoralReportTemplate: "/master-data/sectoral-template-setup",
  sectoralReportTemplateForm:
    "/master-data/sectoral-template-setup/:fiscalyear",
  programSetup: "/master-data/program-setup",
  sectoralAimAndResultIndicatorSetup:
    "/master-data/sectoral-aim-and-result-indicator-setup",
  priorityGrade: "/master-data/priority-grade-setup",
  priorityOption: "/master-data/priority-option-setup",
  sectoralExpenseSourceCeiling: "/master-data/sectoral-expense-source-ceiling",
  sectoralExpenseSourceCeilingForm:
    "/master-data/sectoral-expense-source-ceiling/:fiscalyear",
  sectoralReport: "/sectoral-report",
  sectoralReportForm: "/sectoral-report/form",
  sectoralReportFormFill: "/sectoral-report/form/:fiscalyear",
  sectoralReportFormDetail:
    "/sectoral-report/form/:fiscalyear/:sectoralReportId/:subSectorId/:status",
  subjectAreaOutcomeIndicatorAndTarget: "/sectoral-report/form/:fiscalyear/:sectoralReportId/:subSectorId/:status/outComeIndicatorTargets",
  detailsOfProgram: "/sectoral-report/form/:fiscalyear/:sectoralReportId/:subSectorId/:status/detailsOfProgram",
  programResourceCostEstimate: "/sectoral-report/form/:fiscalyear/:sectoralReportId/:subSectorId/:status/programResourceCostEstimate",
  subSectorSection: "/sectoral-report/form/:fiscalyear/:sectoralReportId/:subSectorId/:status/subSectorSection",
  midTermReport: '/mid-term',
  midTermReportForm: '/mid-term/form',
  midTermReportFormFill: "/mid-term/form/:fiscalyear",
  midTermReportFormDetail:
    "/mid-term/form/:fiscalyear/:midTermReportId",
  midTermFiscalFrameworkDetail: "/mid-term/form/:fiscalyear/:midTermReportId/fiscalFrameworkdetail",
  aimAndResultIndicatorDetailController: "/mid-term/form/:fiscalyear/:midTermReportId/aimAndResultIndicatorDetailController",
  mediumTermBudgetFramework: "/mid-term/form/:fiscalyear/:midTermReportId/mediumTermBudgetFramework",
  thematicParagraph: "/mid-term/form/:fiscalyear/:midTermReportId/thematicParagraph",
  midYearFinancialAim: '/master-data/financial-aim-master-data',
  mediumTermResultFramework: "/master-data/medium-term-result-framework"
};
