export enum DYNAMICFORMFIELDTYPE {
  SELECT = 'SELECT',
  MULTISELECT = 'MULTISELECT',
  TEXT = 'TEXT',
  NUMBER = 'NUMBER',
  NEPALICALENDAR = 'NEPALIDATEPICKER',
  ENGLISHCALENDAR = 'ENGLISHDATEPICKER',
  RADIO = 'RADIO',
  CHECKBOX = 'CHECKBOX',
  TEXTAREA = 'TEXTAREA',
  INPUT = 'INPUT',
}
