export enum DYNAMICFORMFIELDTYPE {
  SELECT = 'SELECT',
  MULTISELECT = 'MULTISELECT',
  TEXT = 'TEXT',
  NUMBER = 'NUMBER',
  NEPALICALENDAR = 'NEPALICALENDAR',
  ENGLISHCALENDAR = 'ENGLISHCALENDAR',
  RADIO = 'RADIO',
  CHECKBOX = 'CHECKBOX',
  TEXTAREA = 'TEXTAREA',
  INPUT = 'INPUT',
}
