export enum PRIVILEGEENUM {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  READ_LIST = 'READ_LIST',
  FORWARD = 'FORWARD',
  VERIFY = 'VERIFY',
  SUBMIT = 'SUBMIT',
  APPROVE = 'APPROVE',
  BACK_FOR_REVIEW = 'BACK_FOR_REVIEW',
  REJECT = 'REJECT',
}
